domain_path: D:\Lab\Project\FPGA_accel\workspace\hm_workspace\zcu104_platform\export\zcu104_platform\sw\standalone_psu_cortexa53_0
app_src_dir: D:\Programs\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
